tclmode

# Generated by Genus(TM) Synthesis Solution 19.12-s121_1, revision 1.385c
# Generated on: Tue Apr 01 15:34:04 CST 2025 (Tue Apr 01 07:34:04 GMT 2025)

set_screen_display -noprogress
set_dofile_abort exit

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

tcl_set_command_name_echo on

set_log_file fv/MultTop/rtl_to_fv_map.log -replace

usage -auto -elapse

set_verification_information rtl_fv_map_db

read_implementation_information fv/MultTop -revised fv_map

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set env(RC_VERSION)     "19.12-s121_1"
set env(CDN_SYNTH_ROOT) "/soft/cadence/genus/19.12.000/tools.lnx86"
set CDN_SYNTH_ROOT      "/soft/cadence/genus/19.12.000/tools.lnx86"
set env(CW_DIR) "/soft/cadence/genus/19.12.000/tools.lnx86/lib/chipware"
set CW_DIR      "/soft/cadence/genus/19.12.000/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path . /soft/cadence/genus/19.12.000/tools.lnx86/lib/tech -library -both
read_library -liberty -both /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_AO_RVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_AO_LVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_AO_SLVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_AO_SRAM_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_INVBUF_LVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_INVBUF_RVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_INVBUF_SLVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_INVBUF_SRAM_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_OA_LVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_OA_RVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_OA_SLVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_OA_SRAM_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_SEQ_LVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_SEQ_RVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_SEQ_SLVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_SEQ_SRAM_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_SIMPLE_LVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_SIMPLE_RVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_SIMPLE_SLVT_TT_nldm_201020.lib.gz /home/yukunw/asap7-ry/asap7sc7p5t_27/LIB/NLDM/asap7sc7p5t_SIMPLE_SRAM_TT_nldm_201020.lib.gz

set_undriven_signal 0 -golden
set_naming_style rc -golden
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue. This option is
# only available with LEC 17.20-d301 or later.
set lec_version_required "17.20301"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -const_port_extend
}
set_hdl_options -VERILOG_INCLUDE_DIR "incdir:sep:src:cwd"

add_search_path . -design -golden
read_design -enumconstraint -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -sv09  /home/yukunw/dacs-lab3/experiment/dacs2024/lab3/results/26631dadda_bit16fb6545dd58885bf2431c21988dff9e3bddef7e0086f449065a0c1e66cdebbb80/mult.v
elaborate_design -golden -root {MultTop} -rootonly 

read_design -verilog95   -revised -lastmod -noelab fv/MultTop/fv_map.v.gz
elaborate_design -revised -root {MultTop}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

set_flatten_model -balanced_modeling

set_analyze_option -auto -report_map

write_hier_compare_dofile hier_tmp1.lec.do -noexact_pin_match -constraint -usage \
-replace -balanced_extraction -input_output_pin_equivalence \
-prepend_string "report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose ; analyze_datapath  -verbose"
run_hier_compare hier_tmp1.lec.do -dynamic_hierarchy

report_hier_compare_result -dynamicflattened

report_verification -hier -verbose

write_verification_information
report_verification_information

# Reports how effective the implementation information was.
# This command is only available with LEC 18.20-d330 or later.
set lec_version_required "18.20330"
if {$lec_version >= $lec_version_required} {
    report_implementation_information
}

set_system_mode lec

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
# This command is available with LEC 19.10-p100 or later.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required} {
    analyze_results -logfiles fv/MultTop/rtl_to_fv_map.log
}

vpxmode

exit -f
